services:
  frontend:
    image: "ghcr.io/mechance782/salamander-frontend:latest"
    ports:
      - "3001:3000"
  backend:
    image: "ghcr.io/mechance782/salamander:latest"
    ports:
      - "3000:3000"
    volumes:
      - "${VIDEO_DIR}:/videos"

    